<?php

/*
 * This file is licensed under GPLv2+.
*/

/**
 * @file
 * Provides features interacting with kuaidi100 api.
 */

/**
 * Implementation of hook_menu().
 */
function kuaidi100_menu() {
	$items['admin/config/services/kuadi100'] = array(
		'title' => 'kuaidi100 settings',
		'description' => 'kuaidi100 configuration',
		'access arguments' => array('access administration pages'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('kuaidi100_admin_form'),
	);
	return $items;
}

function kuaidi100_admin_form($form, $form_state) {
	$form=array(
		'#validate' => array('kuaidi100_admin_form_validate'),
		'#submit' => array('kuaidi100_admin_form_submit'),
	);
	$form['siteurl']=array(
		'#type' => 'item',
		'#title' => t('Current site URL'),
		'#markup' => $GLOBALS['base_root'],
	);
	$form['key']=array(
		'#type' => 'textfield',
		'#title' => t('Your api key'),
		'#description' => t('Please go <a href="@url">here</a> to apply your api key.', array('@url'=>'http://www.kuaidi100.com/openapi/')),
		'#required' => TRUE,
		'#size' => 20,
		'#maxlength' => 16,
		'#default_value' => variable_get('kuaidi100_api_key', ''),
	);
	return system_settings_form($form);
}

function kuaidi100_admin_form_validate($form, $form_state) {
	if(empty($form_state['values']['key'])) return;
	$url=sprintf('http://api.kuaidi100.com/api?id=%s&com=yuantong&nu=000000&show=0', $form_state['values']['key']);
	$response=drupal_http_request($url);
	if($response->code != '200') {
		form_set_error('key', t('There are communicate error connecting kuaidi100, please try later.'));
		return;
	}
	$resp=json_decode($response->data);
	if($resp->status=='0' && is_null($resp->pattern))
		form_set_error('key', $resp->message);
	
}

function kuaidi100_admin_form_submit($form, $form_state) {
	variable_set('kuaidi100_api_key', $form_state['values']['key']);
}

function kuaidi100_query($com, $orderno) {
	$pattern='http://api.kuaidi100.com/api?id=%s&com=%s&nu=%s&show=0&muti=0';
	$url=sprintf($pattern, variable_get('kuaidi100_api_key', ''), $com, $orderno);
	$response=drupal_http_request($url);
	if($response->code != '200') {
		return FALSE;
	}
	$resp=json_decode($response->data);
	switch($resp->status) {
		case 1:
			switch($resp->state) {
				case 3: return TRUE;
				default: return array('state' => $resp->state, 'message' => $resp->message);
			}
			break;
		default: return FALSE;
	}
}

/**
 * Implementation of hook_cron().
 */
function kuaidi100_cron() {
	$query=db_select('deliverlog','dl')->fields('dl')->condition(db_or()->condition('dl.status',3, '<>')->isNull('dl.status'));
	$result=$query->execute();
	foreach($result as $r) {
		$q=kuaidi100_query($r->com, $r->orderno);
		if($q===TRUE)
			db_update('deliverlog')->condition('com',$r->com)->condition('orderno',$r->orderno)->fields(array(
				'status'=>3,
				'statustext' => t('Delivered'),
			))->execute();
		else if($q==FALSE)
			db_update('deliverlog')->condition('com',$r->com)->condition('orderno',$r->orderno)->fields(array(
				'status'=>$r->status-1,
				'statustext' => t('Error'),
			))->execute();
		else 
			db_update('deliverlog')->condition('com',$r->com)->condition('orderno',$r->orderno)->fields(array(
				'status'=>$q->state,
				'statustext' => $q->message,
			))->execute();
	}
}

/**
 *  * Implementation of hook_uninstall().
 *   */
function kuaidi100_uninstall() {
	variable_del('kuaidi100_api_key');
}

