<?php

/*
 * This file is licensed under GPLv2+.
*/

/**
 * @file
 * Provides features interacting with kuaidi100 api.
 */

/**
 * Implementation of hook_help().
 */
function kuaidi100_help($path, $arg) {
	switch($path) {
		case 'admin/config/services/kuaidi100':
			$num=db_select('deliverlog','d')->fields('d',array('com','orderno'))->distinct()->countQuery()->execute()->fetchField();
			if($num>0) {
				$n=db_select('deliverlog','d')->fields('d',array('com','orderno'))->condition('d.status',3)->distinct()->countQuery()->execute()->fetchField();
				if($n>0)
					if($n==$num)
						$output=t('Kuaidi100 has tracked @num orders for you, all of them have been delivered.',array('@num'=>$num));
					else
						$output=t('Kuaidi100 has tracked @num orders for you, while @n of them have been delivered.',array('@num'=>$num, '@n'=>$n));
				else
					$output=t('Kuaidi100 has tracked @num orders for you, none of them has been delivered till now.',array('@num'=>$num));
			}
	}
	if(isset($output))
		return $output;
}

/**
 * Implementation of hook_menu().
 */
function kuaidi100_menu() {
	$items['admin/config/services/kuaidi100'] = array(
		'title' => 'kuaidi100 settings',
		'description' => 'kuaidi100 configuration',
		'access arguments' => array('access administration pages'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('kuaidi100_admin_form'),
	);
	return $items;
}

function kuaidi100_admin_form($form, $form_state) {
	$form=array(
		'#validate' => array('kuaidi100_admin_form_validate'),
		'#submit' => array('kuaidi100_admin_form_submit'),
	);
	$form['siteurl']=array(
		'#type' => 'item',
		'#title' => t('Current site URL'),
		'#markup' => $GLOBALS['base_root'],
	);
	$form['key']=array(
		'#type' => 'textfield',
		'#title' => t('Your api key'),
		'#description' => t('Please go <a href="@url" target="_blank">here</a> to apply your api key.', array('@url'=>'http://www.kuaidi100.com/openapi/')),
		'#required' => TRUE,
		'#size' => 20,
		'#maxlength' => 16,
		'#default_value' => variable_get('kuaidi100_api_key', ''),
	);
	return system_settings_form($form);
}

function kuaidi100_admin_form_validate($form, $form_state) {
	if(empty($form_state['values']['key'])) return;
	$url=sprintf('http://api.kuaidi100.com/api?id=%s&com=yuantong&nu=000000&show=0', $form_state['values']['key']);
	$response=drupal_http_request($url);
	if($response->code != '200') {
		form_set_error('key', t('There are communicate error connecting kuaidi100, please try later.'));
		return;
	}
	$resp=json_decode($response->data);
	if($resp->status=='0' && is_null($resp->pattern))
		form_set_error('key', $resp->message);
	
}

function kuaidi100_admin_form_submit($form, $form_state) {
	variable_set('kuaidi100_api_key', $form_state['values']['key']);
}

function kuaidi100_update_status($com, $orderno) {
	$pattern='http://api.kuaidi100.com/api?id=%s&com=%s&nu=%s&show=0&muti=0';
	$url=sprintf($pattern, variable_get('kuaidi100_api_key', ''), $com, $orderno);
	$referrer=$GLOBALS['base_root'];
	if(in_array($com, array('shunfeng','ems','shentong'))) {
		$url=sprintf('http://www.kuaidi100.com/applyurl?key=%s&com=%s&nu=%s', variable_get('kuaidi100_api_key', ''), $com, $orderno);
		$response=drupal_http_request($url);
		if($response->code != '200') return;
		$pattern='http://www.kuaidi100.com/query?id=1&type=%s&postid=%s';
		$url=sprintf($pattern, $com, $orderno);
		$referrer=$response->data;
	}
		
	$response=drupal_http_request($url, array(
		'headers'=>array(
			'Referer'=>$referrer,
			'Content-Type'=>'application/x-www-form-urlencoded',
		)
	));
	if($response->code != '200') {
		return;
	}
	$resp=json_decode(preg_replace('/\'/','"',$response->data));
	if(isset($resp->status)) settype($resp->status, 'integer');
	if(isset($resp->state)) settype($resp->status, 'integer');
	
	switch($resp->status) {
		case 1:
		case 200:
			if($resp->state==3)
				$d=date_parse_from_format('Y-m-d H:i:s', $resp->data[0]->time);
			else
				$d=date_parse_from_format('Y-m-d H:i:s', $resp->updatetime);
			db_update('deliverlog')->condition('com',$com)->condition('orderno',$orderno)->fields(array(
				'status'=>$resp->state,
				'statustext' => $resp->data[0]->context,
				'timestamp' => mktime($d['hour'], $d['minute'], $d['second'], $d['month'], $d['day'], $d['year']),
			))->execute();
			break;
		default:
			$r=db_select('deliverlog','d')->condition('d.com',$com)->condition('d.orderno',$orderno)->fields('d')->execute()->fetchObject();
			db_update('deliverlog')->condition('com',$com)->condition('orderno',$orderno)->fields(array(
				'status'=>$r->status-1,
				'statustext' => $resp->message,
				'timestamp' => time(),
			))->execute();
	}
}

/**
 * Implementation of hook_cron().
 */
function kuaidi100_cron() {
	$query=db_select('deliverlog','dl')->fields('dl',array('com','orderno'))->condition('dl.status',3, '<>')->condition('dl.status',-3,'>')->condition('dl.timestamp',time()-7200,'<')->distinct();
	$result=$query->execute();
	foreach($result as $r) {
		kuaidi100_update_status($r->com, $r->orderno);
	}
}

function kuaidi100_get_status($module, $type) {
	$query=db_select('deliverlog','dl')->fields('dl')->condition('dl.module',$module)->condition('dl.type',$type);
	$result=$query->execute();
	if($result->rowCount()==0) return FALSE;
	else return $result->fetchObject();
}

function kuadi100_resolve_state_code($code=NULL) {
	switch($code) {
		case -4:
		case -3:
		case -2:
		case -1: return t('Error');
		case 0: return t('Delivering');
		case 1: return t('Detached');
		case 2: return t('Under difficulty');
		case 3: return t('Delivered');
		case 4: return t('Refunded');
		default: return FALSE;
	}
}

function kuaidi100_save($module, $type, $com, $orderno) {
	db_merge('deliverlog')
		->key(array('module' => $module, 'type' => $type))
		->fields(array(
			'com' => $com,
			'orderno' => $orderno
		))->execute();
	kuaidi100_update_status($com, $orderno);
}

/**
 *  * Implementation of hook_uninstall().
 *   */
function kuaidi100_uninstall() {
	variable_del('kuaidi100_api_key');
}

